### ISSUE TITLE
Homey-Tahoma my button on remote

### ISSUE THREAD

**Issue by LLV8531** [totalimmersion/com.somfy.tahoma#19]
Hi,

I use the Tahomabox together with homy, all my devices are working well for opening and closing the blinds with flows. On each remote i defined the 'my' button on a specific position of the blind.
In the flows i can use 'open' and 'close' (working well), but if i choose the third option to activate the 'my position' nothings happens.

What i'm doing wrong ? or is the third option not supported.

Thanks for your advise

Luc Laverge

**Comment by totalimmersion** [comment]
Hi Luc,

As far as I know the 'my position' is only available on remotes. The remotes communicate directly to the devices, without the Tahoma box in between. From what I've seen there is no possibility to activate the my position from within the Tahoma app. Therefore this possibility is also not available in Homey, because Homey communicates with Tahoma and not directly to the devices. Now, I could be wrong, if you know a way to activate the my position from within the Tahoma app, please let me know, so I can look into it.

Best regards,

Lennart

**Comment by LLV8531** [comment]
Thanks for your answer. Is it possibe to use the flows (scenarios) made in the Tahoma in the Homey App.
I didn't find it, so I think it's (not) yet implemented in your app ?

Luc

**Comment by totalimmersion** [comment]
Yes, you can use Tahoma scenarios in Homey (see screenshot):
![screen shot 2018-07-13 at 12 02 03](https://user-images.githubusercontent.com/1247198/42685973-cd709ef0-8694-11e8-844d-321725c916bf.png)

Best,

Lennart
