### ISSUE TITLE
Succesful connection but no devices

### ISSUE THREAD

**Issue by CyberRATTLER** [totalimmersion/com.somfy.tahoma#4]
Hi,

I bought the Homey today specifically because there was the support for IO motors.
I made the connection but I can't seem to find any devices.

I'm new to Homey and all this so I have no clue what to do and how to get them in.

Any help would be very appreciated.

Regards

**Comment by totalimmersion** [comment]
Hi,

Sorry for my late response. I must have missed this issue. My apologies. I have created the TaHoma app for Homey based on my own devices. The probable reason why you are not able to find any devices is because they are probably a little different from mine. In order to support your device, could you please provide me some information regarding your device? I've created some instructions. If you follow these and provide me the information, I'm going to try to support your device as well.

Best regards,

Lennart
[Instructions for the TaHoma devices.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/1411943/Instructions.for.the.TaHoma.devices.pdf)

**Comment by CyberRATTLER** [comment]
Hi Lennart,

That's ok. Thanks for getting back to me.

Included as attachment the requested information. As  it is 5 pages I attached the requested information here rather than post in on github and clutter the thread.

If you prefer I post it there anyway just let me know.

For your convenience I have the information both in Word and PDF format.

I have an additional question: since the last update (compatibility with SDK2) your Tahoma app no longer seems to function. It stays connecting forever. Is there something I have to change to my Homey in order to allow compatibility with SDK2?

Thanks for your help.

Regards,

Chris
________________________________

**Comment by totalimmersion** [comment]
Hi Chris,

Unfortunately Github seems to destroy the attachment, because it wasn't attached to the mail. Could you attach it in github?

Version 1.2.0 indeed broke a few things. I've fixed this in 1.2.1 (which is available in the app store since monday), including the issue you describe. If you're having the same issue with 1.2.1 as well, please let me know.

Best,

Lennart

**Comment by CyberRATTLER** [comment]
Hi Lennart,

Included both the attachments.
The other problem is indeed fixed in version 1.2.1.

Thanks again for the help.

Regards,

Chris

[Requested info IO motor.docx](https://github.com/totalimmersion/com.somfy.tahoma/files/1419649/Requested.info.IO.motor.docx)
[Requested info IO motor.pdf](https://github.com/totalimmersion/com.somfy.tahoma/files/1419650/Requested.info.IO.motor.pdf)

**Comment by totalimmersion** [comment]
Thanks Chris, with this information I will be able to support your rollershutters. I will let you know when I'm finished with the implementation.

Best,

Lennart

**Comment by CyberRATTLER** [comment]
Hi Lennart,

Thanks a lot.
Much appreciated.

Regards,

Chris
________________________________

**Comment by totalimmersion** [comment]
Hi Chris,

I wanted to let you know that I've finished the development of several new devices (including yours). The latest version (1.3.0) is now available in the app store. Could you please let me know if everything works as expected?

Best,

Lennart

**Comment by CyberRATTLER** [comment]
Hi Lennart,

I was able to add my shutters so thanks a lot for this.

I noticed however that I can't open or close them without pushing the stop button first.
Is this because of the conversion or is this because some tweaking is needed.

Already many thanks for the current changes.

Regards,

Chris
________________________________

**Comment by CyberRATTLER** [comment]
Hi Lennart,

Ignore my previous message.
It's only the first time. After that it works as required.

Thanks a lot.

Chris

Sent from Blue<http://www.bluemail.me/r?b=11012>
On 30 Oct 2017, at 19:19, totalimmersion <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Chris,

I wanted to let you know that I've finished the development of several new devices (including yours). The latest version (1.3.0) is now available in the app store. Could you please let me know if everything works as expected?

Best,

Lennart

**Comment by totalimmersion** [comment]
Good to hear Chris,

Yes, it's possible the first time, because of a mismatch of the states between Homey and Tahoma. But once Homey synchronizes itself with Tahoma (which happens every minute), it works as expected.

I'm closing this issue now. If you have any further questions, or if you would like to have some other devices added in the future, please create a new issue for that.

Best,

Lennart
